# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

altra <- function(v, n, ind, nodes) {
    .Call('_TreeGuidedRegression_altra', PACKAGE = 'TreeGuidedRegression', v, n, ind, nodes)
}

findLambdaMax <- function(v, n, ind, nodes) {
    .Call('_TreeGuidedRegression_findLambdaMax', PACKAGE = 'TreeGuidedRegression', v, n, ind, nodes)
}

treeNorm <- function(x, n, ind, nodes) {
    .Call('_TreeGuidedRegression_treeNorm', PACKAGE = 'TreeGuidedRegression', x, n, ind, nodes)
}

eplb <- function(v, n, z, lambda0) {
    .Call('_TreeGuidedRegression_eplb', PACKAGE = 'TreeGuidedRegression', v, n, z, lambda0)
}

general_altra <- function(v, n, G, ind, nodes) {
    .Call('_TreeGuidedRegression_general_altra', PACKAGE = 'TreeGuidedRegression', v, n, G, ind, nodes)
}

general_findLambdaMax <- function(v, n, G, ind, nodes) {
    .Call('_TreeGuidedRegression_general_findLambdaMax', PACKAGE = 'TreeGuidedRegression', v, n, G, ind, nodes)
}

general_treeNorm <- function(x, n, G, ind, nodes) {
    .Call('_TreeGuidedRegression_general_treeNorm', PACKAGE = 'TreeGuidedRegression', x, n, G, ind, nodes)
}

rcpp_hello_world <- function() {
    .Call('_TreeGuidedRegression_rcpp_hello_world', PACKAGE = 'TreeGuidedRegression')
}

